=== lanl-ansi/PowerModelsONM.jl/schemas/runtime_arguments.schema.json
{
  "meta:license": [
    "Copyright (c) 2020, Triad National Security, LLC.",
    "This code is provided under a BSD license as part of the Multi-Infrastructure Control",
    "and Optimization Toolkit (MICOT) project, LA-CC-13-108.",
    "You may not use this file except in compliance with the License. You may obtain a copy",
    "of the License at https://github.com/lanl-ansi/PowerModelsONM.jl/blob/main/LICENSE.md"
  ],
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "schemas/runtime_arguments",
  "type": "object",
  "title": "Runtime arguments",
  "additionalProperties": false,
  "properties": {
    "network": {
      "type": "string"
    },
    "output": {
      "type": "string"
    },
    "faults": {
      "type": "string"
    },
    "events": {
      "type": "string"
    },
    "inverters": {
      "type": "string"
    },
    "settings": {
      "type": "string"
    },
    "quiet": {
      "type": "boolean",
      "default": false
    },
    "verbose": {
      "type": "boolean",
      "default": false
    },
    "debug": {
      "type": "boolean",
      "default": false
    },
    "gurobi": {
      "type": "boolean",
      "default": false
    },
    "opt-disp-formulation": {
      "type": "string",
      "enum": [
        "acp",
        "acr",
        "lindistflow",
        "nfa"
      ]
    },
    "network-file": {
      "type": "string",
      "deprecated": true
    },
    "output-file": {
      "type": "string",
      "deprecated": true
    },
    "problem": {
      "type": "string",
      "deprecated": true,
      "enum": [
        "opf",
        "mld"
      ]
    },
    "formulation": {
      "type": "string",
      "deprecated": true,
      "enum": [
        "acr",
        "acp",
        "lindistflow",
        "nfa"
      ]
    },
    "protection-settings": {
      "type": "string",
      "deprecated": true
    },
    "debug-export-file": {
      "type": "string",
      "deprecated": true
    },
    "use-gurobi": {
      "type": "boolean",
      "default": false,
      "deprecated": true
    },
    "solver-tolerance": {
      "type": "number",
      "default": 0.0001,
      "deprecated": true
    },
    "max-switch-actions": {
      "type": "integer",
      "default": 0,
      "deprecated": true
    },
    "timestep-hours": {
      "type": "number",
      "default": 1,
      "deprecated": true
    },
    "voltage-lower-bound": {
      "default": 0.8,
      "deprecated": true,
      "type": "number"
    },
    "voltage-upper-bound": {
      "type": "number",
      "default": 1.2,
      "deprecated": true
    },
    "voltage-angle-difference": {
      "type": "number",
      "default": 5,
      "deprecated": true
    },
    "clpu-factor": {
      "type": "number"
    }
  },
  "x-tags": [
    "input"
  ],
  "examples": [
    {
      "network": "../test/data/IEEE13Nodeckt_mod.dss",
      "gurobi": false,
      "settings": "../test/data/settings.json",
      "faults": "../test/data/faults.json",
      "inverters": "../test/data/inverters.json",
      "events": "../test/data/events.json",
      "quiet": true,
      "opt-disp-formulation": "acr"
    }
  ],
  "description": "The allowed runtime arguments for PowerModelsONM's entrypoint"
}

=== lanl-ansi/PowerModelsONM.jl/test/data/runtime_args_example.json
{
    "network": "../test/data/IEEE13Nodeckt_mod.dss",
    "gurobi": false,
    "settings": "../test/data/settings.json",
    "faults": "../test/data/faults.json",
    "inverters": "../test/data/inverters.json",
    "events": "../test/data/events.json",
    "quiet": true,
    "opt-disp-formulation": "acr"
}
